language: node_js
node_js:
- '0.10'
install:
- bin/installDeps.sh
- export GIT_HASH=$(git rev-parse --verify --short HEAD)
- ! 'echo "web: node node_modules/ep_etherpad-lite/node/server.js" > Procfile'
- cp src/package.json ./
- npm install
- zip -r etherpad-lite-cf-orange ./*
deploy:
  provider: releases
  api_key:
    secure: dkDukVdLcR42bUekW7bN5uL627YzRaJzbqAqhSWkMiy7ezrYSA54HY4RVhpG45NRtO4XGfbR68ljpq2z/H/lcAHsira35uCsLxWfa6Z7fhkLLe4EJrqRf8BsSAxsT9DFWSLNYOxrLlRvvF+pELR9OBcMq3dNg/svBSUX8c3+MzY=
  file: etherpad-lite-cf-orange.zip
  on:
    tags: true
    all_branches: true
